version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
